# Generated by Django 4.0.3 on 2022-05-16 08:35

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime.now),
        ),
    ]
