# Generated by Django 4.0.3 on 2022-05-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_course_audience_course_audience_and_more'),
        ('online_course', '0003_alter_onlinecoursecategory_options_and_more'),
        ('users', '0002_alter_profile_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='course.course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='online_course',
            field=models.ManyToManyField(blank=True, null=True, to='online_course.onlinecourse'),
        ),
    ]
