# Generated by Django 4.0.3 on 2022-05-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=120)),
                ('slider_alt', models.TextField(default='')),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='store_image/sliders_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
