# Generated by Django 4.0.3 on 2022-05-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='slider_alt',
            new_name='alt',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='slider_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='slider_title',
            new_name='title',
        ),
    ]
