# Generated by Django 4.0.3 on 2022-05-16 06:24

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_audience',
            new_name='audience',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_discount_percent',
            new_name='discount_percent',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_discounted_price',
            new_name='discounted_price',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_prerequisites',
            new_name='prerequisites',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_related_category',
            new_name='related_category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_syllabus',
            new_name='syllabus',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_targets',
            new_name='targets',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='coursecategory',
            old_name='course_category',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_start_date',
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime.now),
        ),
    ]
