# Generated by Django 4.0.3 on 2022-05-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('online_course', '0001_initial'),
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='online_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online_course.onlinecourse'),
        ),
    ]
