# Generated by Django 4.0.3 on 2022-05-16 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_course', '0002_initial'),
        ('course', '0002_rename_course_audience_course_audience_and_more'),
        ('certification', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title_fani', models.CharField(max_length=50)),
                ('code_fani', models.CharField(default='1234567890', max_length=10)),
                ('code_academy', models.CharField(default='1234567890', max_length=10)),
                ('certificate_image_academy', models.ImageField(blank=True, null=True, upload_to='store_image/certificate_academy_image/')),
                ('certificate_image_fani', models.ImageField(blank=True, null=True, upload_to='store_image/certificate_fani_image/')),
                ('fani_score', models.PositiveIntegerField(default='100')),
                ('academy_score', models.PositiveIntegerField(default='100')),
                ('date', django_jalali.db.models.jDateTimeField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('online_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online_course.onlinecourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
