# Generated by Django 4.0.3 on 2022-05-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_order', models.IntegerField(default=1)),
                ('chapter_title', models.CharField(default='', max_length=100)),
                ('chapter_description', models.TextField(default='')),
                ('chapter_duration', models.TimeField(default='')),
                ('number_of_episode', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_order', models.IntegerField(default=1)),
                ('episode_title', models.CharField(default='', max_length=100)),
                ('episode_description', models.TextField(default='')),
                ('episode_duration', models.TimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_course_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_course_title', models.CharField(default='', max_length=100)),
                ('online_course_price', models.IntegerField(default=1)),
                ('online_course_discount_percent', models.IntegerField(default=0)),
                ('online_course_discounted_price', models.IntegerField(default=1)),
                ('online_course_description', models.TextField(default='')),
                ('online_course_duration', models.DurationField(default=172800.0)),
                ('online_course_image', models.ImageField(default='', upload_to='images/')),
                ('number_of_videos', models.IntegerField(default=1)),
                ('online_course_level', models.CharField(choices=[('مبتدی', 'Beginner'), ('متوسط', 'Intermediate'), ('حرفه ای', 'Proffessional')], default='مبتدی', max_length=100)),
                ('online_course_status', models.CharField(choices=[('پیش ثبت نام', 'Pre Registration'), ('در حال برگزاری', 'Running'), ('برگزار شده', 'Done')], default='در حال برگزاری', max_length=100)),
                ('online_course_start_date', models.DateTimeField(auto_now_add=True)),
                ('online_course_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_course.onlinecoursecategory')),
                ('online_course_related_category', models.ManyToManyField(related_name='online_rel_cat', to='online_course.onlinecoursecategory')),
            ],
        ),
    ]
