# Generated by Django 4.0.3 on 2022-05-15 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecourse',
            name='online_course_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='episode',
            name='related_to_chapter',
            field=models.ManyToManyField(to='online_course.chapter'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='related_to_online_course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='online_course.onlinecourse'),
        ),
    ]
