# Generated by Django 4.0.3 on 2022-05-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinecoursecategory',
            options={'verbose_name_plural': 'Online course categories'},
        ),
        migrations.RenameField(
            model_name='onlinecourse',
            old_name='online_course_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='onlinecourse',
            old_name='online_course_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='onlinecourse',
            old_name='online_course_discount_percent',
            new_name='discount_percent',
        ),
        migrations.RenameField(
            model_name='onlinecourse',
            old_name='online_course_discounted_price',
            new_name='discounted_price',
        ),
        migrations.RenameField(
            model_name='onlinecourse',
            old_name='online_course_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='onlinecourse',
            old_name='online_course_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='onlinecourse',
            old_name='online_course_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='onlinecourse',
            old_name='online_course_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='onlinecourse',
            old_name='online_course_related_category',
            new_name='related_category',
        ),
        migrations.RenameField(
            model_name='onlinecourse',
            old_name='online_course_start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='onlinecourse',
            old_name='online_course_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='onlinecourse',
            old_name='online_course_teacher',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='onlinecourse',
            old_name='online_course_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='onlinecoursecategory',
            old_name='online_course_category',
            new_name='category',
        ),
    ]
