# Generated by Django 4.0.3 on 2022-05-16 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store_image/social-media')),
                ('alt', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Social media',
                'verbose_name_plural': 'Social media',
            },
        ),
        migrations.RemoveField(
            model_name='footer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='footer_about_us',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='footer_insta',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='footer_phone',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='footer_telegram',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='footer_whats_app',
        ),
        migrations.AddField(
            model_name='footer',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='social_media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='footer.social'),
            preserve_default=False,
        ),
    ]
