# Generated by Django 4.0.3 on 2022-05-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='menucategory',
            old_name='menu_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='menucategory',
            old_name='menu_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu_item_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu_item_title',
            new_name='title',
        ),
    ]
