# Generated by Django 4.0.3 on 2022-07-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menucategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='created_at',
        ),
    ]
