# Generated by Django 3.2.7 on 2022-01-24 07:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('INTERNAL_MANAGER', 'مدیر داخلی'), ('GENERAL_MANAGER', 'مدیر اصلی'), ('TEACHER', 'مدرس'), ('FINANCIAL', 'امور مالی'), ('TECHNICAL ISSUES', 'مشکلات فنی')], default=('INTERNAL_MANAGER', 'مدیر داخلی'), max_length=100)),
                ('what_course', models.CharField(choices=[('ONLINE COURSE', 'دوره ی مجازی'), ('COURSE', 'دوره ی حضوری')], default=('ONLINE COURSE', 'دوره ی مجازی'), max_length=100)),
                ('ticket_title', models.CharField(default='', max_length=100)),
                ('ticket_message', models.TextField()),
                ('ticket_file', models.FileField(blank=True, default='', null=True, upload_to='files/ticket_files/')),
                ('ticket_status', models.CharField(choices=[('OPEN', 'باز'), ('CLOSED', 'بسته'), ('ANSWERD', 'پاسخ داده شده'), ('FINISHED', 'پایان یافته'), ('IN PROGRESS', 'درحال بررسی')], default=('OPEN', 'باز'), max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
            ],
        ),
    ]
