# Generated by Django 3.2.7 on 2022-01-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='ticket_id',
        ),
    ]
