# Generated by Django 3.2.7 on 2022-01-24 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticketmessage_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket'),
        ),
    ]
