# Generated by Django 3.2.7 on 2022-01-24 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticketmessage_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket message+', to='ticket.ticket', to_field='ticket_message'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('ticket_message',), name='unique'),
        ),
    ]
