# Generated by Django 3.2.7 on 2022-01-25 08:17

from django.db import migrations, models
import ticket.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20220124_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='identical',
            field=models.CharField(default=ticket.utils.create_new_number, editable=False, max_length=10, unique=True),
        ),
    ]
