# Generated by Django 3.2.7 on 2022-01-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_ticket_identical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_message',
        ),
    ]
