# Generated by Django 3.2.7 on 2022-01-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_remove_ticket_ticket_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
