# Generated by Django 3.2.7 on 2022-01-26 11:12

from django.db import migrations, models
import ticket.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_alter_ticketmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='identical',
            field=models.IntegerField(default=ticket.utils.create_new_number, editable=False, max_length=10, unique=True),
        ),
    ]
